
package teslimedilecekproje;

import java.util.ArrayList;

/**
 * @author yusuf
 */
public class Bolum extends javax.swing.JFrame {
    BolumDB bolumIslemleri = new BolumDB();
    ArrayList <ArrayList> bolumler = new ArrayList();
    ArrayList <ArrayList> iliskiliBolumler = new ArrayList();
    ArrayList <ArrayList> basibosBolumler = new ArrayList();
    ArrayList <ArrayList> fakulteler = new ArrayList();
    AnaMenu a;
    int ID,ID2,ID3,ID4,ID5;
    /**
     * Creates new form Bolum
     */
    public Bolum() {
        initComponents();
        setTitle("Bölüm işlmeleri");
        setLocation(500, 200);
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox4Yenile();
        ComboBox5Yenile();
    }

    public void ComboBox1Yenile()
    {
        jComboBox1.removeAllItems();
        bolumler = bolumIslemleri.BolumListele();
        for(ArrayList bolum:bolumler)
        {
            jComboBox1.addItem(bolum.get(1).toString());
        }
        jComboBox1.setSelectedIndex(-1);
        ComboBox5Yenile();
    }
    
    public void ComboBox2Yenile()
    {
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        fakulteler = bolumIslemleri.FakulteListele();
        for(ArrayList fakulte:fakulteler)
        {
            jComboBox2.addItem(fakulte.get(1).toString());
            jComboBox3.addItem(fakulte.get(1).toString());
        }
        jComboBox2.setSelectedIndex(-1);
        jComboBox3.setSelectedIndex(-1);
    }
    
    public void ComboBox4Yenile()
    {
        jComboBox4.removeAllItems();
        iliskiliBolumler = bolumIslemleri.IliskiliBolumListele(ID3);
        for(ArrayList bolum:iliskiliBolumler)
        {
            jComboBox4.addItem(bolum.get(2).toString());
        }
        jComboBox4.setSelectedIndex(-1);
    }
    
    public void ComboBox5Yenile()
    {
        jComboBox5.removeAllItems();
        basibosBolumler = bolumIslemleri.BasibosBolumListele(ID3);
        for(ArrayList olanBolumler:bolumler)
        {
            boolean tekrar=false;
            for(ArrayList bolum:basibosBolumler)
            {
                if(olanBolumler.get(0).toString().equals(bolum.get(1).toString()))
                {
                    tekrar=true;
                }
            }
            if(!tekrar)
            {
                jComboBox5.addItem(olanBolumler.get(1).toString());
            }
        }
        if(ID3==-1)
        {
            jComboBox5.removeAllItems();
        }
        jComboBox5.setSelectedIndex(-1);
    }
    
    public void anamenu(AnaMenu a)
    {
        this.a=a;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setResizable(false);

        label1.setAlignment(java.awt.Label.CENTER);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jTextField1.setToolTipText("Eklemek istediğiniz bölümü giriniz");

        jButton1.setText("Ekle");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Kaydet");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2İtemStateChanged(evt);
            }
        });

        jTextField2.setToolTipText("Eklemek istediğiniz fakülteyi giriniz");

        jButton4.setText("Ekle");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Kaydet");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Sil");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jComboBox3.setToolTipText("İlişkilendirmek istediğiniz ya da ilişkiyi kaldıracağınız fakülteyi seçiniz");
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3İtemStateChanged(evt);
            }
        });

        jComboBox4.setBackground(new java.awt.Color(180, 30, 30));
        jComboBox4.setForeground(new java.awt.Color(245, 120, 21));
        jComboBox4.setToolTipText("İlişkiyi kaldıracağınız bölümü seçiniz");
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4İtemStateChanged(evt);
            }
        });

        jButton7.setText("ilişkilendir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(180, 30, 30));
        jButton8.setForeground(new java.awt.Color(245, 120, 21));
        jButton8.setText("ilişkiyi kaldır");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("AnaMenü");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jComboBox5.setToolTipText("İlişkilendireceğiniz bölümü seçiniz");
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5İtemStateChanged(evt);
            }
        });

        jLabel1.setText("Bölüm");

        jLabel2.setText("Fakülte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jComboBox2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jTextField2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String text = jTextField1.getText();
        if(text.equals(""))
        {
            System.out.println("En az 1 karakter girmeden bölüm ekleyemezsiniz");
        }
        else
        {
            String text1 = text.toUpperCase();
            boolean tekrar = false;
            for(ArrayList bolum:bolumler)
            {
                String text2 = bolum.get(1).toString().toUpperCase();
                if (text2.equals(text1))
                {
                    tekrar=true;
                }
            }
            if(tekrar)
            {
                jDialog1.setVisible(true);
                jDialog1.setSize(300,100);
                jDialog1.setLocation(500,200);
                jDialog1.setTitle("Zaten böyle bir kayıt var");
                label1.setText("Farklı bir bölüm ismi giriniz...");
            }
            else
            {
                bolumIslemleri.BolumEkle(text);
                ComboBox1Yenile();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String text = jTextField2.getText();
        if(text.equals(""))
        {
            System.out.println("En az 1 karakter girmeden fakülte ekleyemezsiniz...");
        }
        else
        {
            String text1 = text.toUpperCase();
            boolean tekrar = false;
            for(ArrayList fakulte:fakulteler)
            {
                String text2 = fakulte.get(1).toString().toUpperCase();
                if (text2.equals(text1))
                {
                    tekrar=true;
                }
            }
            if(tekrar)
            {
                jDialog1.setVisible(true);
                jDialog1.setSize(300,100);
                jDialog1.setLocation(500,200);
                jDialog1.setTitle("Zaten böyle bir kayıt var");
                label1.setText("Farklı bir fakülte ismi giriniz...");
            }
            else
            {
                if("".equals(text))
                {
                    jDialog1.setVisible(true);
                    jDialog1.setSize(300,100);
                    jDialog1.setLocation(500,200);
                    jDialog1.setTitle("Hiçbirşey yazmamışsınız");
                    label1.setText("Fakülte ekleyebilmemiz için en az 1 karakter harf koyun...");
                }
                else
                {
                    bolumIslemleri.FakulteEkle(text);
                    ComboBox2Yenile();
                }
            }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(ID==-1)
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("Silinecek bir şey bulunamadı");
            label1.setText("Bölüm silebilmek için önce seçmelisiniz...");
        }
        bolumIslemleri.BolumSil(ID);
        ComboBox1Yenile();
        ComboBox4Yenile();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        //yanlış özellik (kullanmayacağım metodu aktif etmişim)
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        if(jComboBox1.getSelectedItem()==null)
        {
            jTextField1.setText("");
            ID=-1;
        }
        else
        {
            String text = jComboBox1.getSelectedItem().toString();
            jTextField1.setText(text);
            text = text.toUpperCase();
            for(ArrayList bolum:bolumler)
            {
                if (bolum.get(1).toString().toUpperCase().equals(text))
                {
                    ID = Integer.parseInt(bolum.get(0).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String text = jTextField1.getText();
        if("".equals(text))
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("Boş bilgi girilemez");
            label1.setText("Düzenleyelim derken silmeye çalıştınız herhalde:)");
        }
        bolumIslemleri.BolumDuzenle(text,ID);
        ComboBox1Yenile();
        ComboBox4Yenile();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String text = jTextField2.getText();
        bolumIslemleri.FakulteDuzenle(text,ID2);
        if("".equals(text))
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("Boş bilgi girilemez");
            label1.setText("Düzenleyelim derken silmeye çalıştınız herhalde:)");
        }
        ComboBox2Yenile();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if(ID2==-1)
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("Silinecek bir şey bulunamadı");
            label1.setText("Fakülte silebilmek için önce seçmelisiniz...");
        }
        bolumIslemleri.FakulteSil(ID2);
        ComboBox2Yenile();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        if(jComboBox2.getSelectedItem()==null)
        {
            jTextField2.setText("");
            ID2=-1;
        }
        else
        {
            String text = jComboBox2.getSelectedItem().toString();
            jTextField2.setText(text);
            text = text.toUpperCase();
            for(ArrayList fakulte:fakulteler)
            {
                if (fakulte.get(1).toString().toUpperCase().equals(text))
                {
                    ID2 = Integer.parseInt(fakulte.get(0).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox2İtemStateChanged

    private void jComboBox3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3İtemStateChanged
        if(jComboBox3.getSelectedItem()==null)
        {
            ID3=-1;
        }
        else
        {
            String text = jComboBox3.getSelectedItem().toString();
            text = text.toUpperCase();
            for(ArrayList fakulte:fakulteler)
            {
                if (fakulte.get(1).toString().toUpperCase().equals(text))
                {
                    ID3 = Integer.parseInt(fakulte.get(0).toString());
                }
            }
        }
        ComboBox4Yenile();
        ComboBox5Yenile();
    }//GEN-LAST:event_jComboBox3İtemStateChanged

    private void jComboBox5İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5İtemStateChanged
        if(jComboBox5.getSelectedItem()==null)
        {
            ID5=-1;
        }
        else
        {
            String text = jComboBox5.getSelectedItem().toString();
            text = text.toUpperCase();
            for(ArrayList bolum:bolumler)
            {
                if (bolum.get(1).toString().toUpperCase().equals(text))
                {
                    ID5 = Integer.parseInt(bolum.get(0).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox5İtemStateChanged

    private void jComboBox4İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4İtemStateChanged
        if(jComboBox4.getSelectedItem()==null)
        {
            ID4=-1;
        }
        else
        {
            String text = jComboBox4.getSelectedItem().toString();
            text = text.toUpperCase();
            for(ArrayList bolum:iliskiliBolumler)
            {
                if (bolum.get(2).toString().toUpperCase().equals(text))
                {
                    ID4 = Integer.parseInt(bolum.get(0).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox4İtemStateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if(jComboBox5.getItemCount()==0 || ID3 == -1 || ID5==-1)
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("seçili bir eleman yok");
            label1.setText("ilişkilendirebilmemiz için Fakülte ve Bölüm seçmelisiniz...");
        }
        else
        {
            bolumIslemleri.Ilıskilendir(ID3, ID5);
        }
        ComboBox4Yenile();
        ComboBox5Yenile();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if(jComboBox4.getItemCount()==0 || ID4 == -1 || ID3 == -1)
        {
            jDialog1.setVisible(true);
            jDialog1.setSize(300,100);
            jDialog1.setLocation(500,200);
            jDialog1.setTitle("seçili bir eleman yok");
            label1.setText("ilişkiyi kaldırabilmemiz için Bölüm ve Fakülte seçmelisiniz...");
        }
        else
        {
            bolumIslemleri.IliskiKaldir(ID4);
        }
        ComboBox4Yenile();
        ComboBox5Yenile();
    }//GEN-LAST:event_jButton8MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox4Yenile();
        ComboBox5Yenile();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bolum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
