
package teslimedilecekproje;

import java.util.ArrayList;

/**
 * @author yusuf
 */
public class Ders extends javax.swing.JFrame {
    FakulteBolumDoldur derslerIslemleri = new DersDB();
    ArrayList <ArrayList> dersler = new ArrayList();
    ArrayList <ArrayList> bolumler = new ArrayList();
    ArrayList <ArrayList> fakulteler = new ArrayList();
    //İsimler aynı olunca diğer fakültelerin dersleri görünmüyor onu düzeltmek için
    
    
    int ID,ID2,ID3;
    AnaMenu a;
    /**
     * Creates new form Ders
     */
    public Ders() {
        initComponents();
        setTitle("Ders işlemleri");
        setLocation(500, 200);
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
    }
    
    
    public void ComboBox1Yenile()
    {
        dersler = derslerIslemleri.Listele();
        jComboBox1.removeAllItems();
        for(ArrayList ders:dersler)
        {
            jComboBox1.addItem(new ComboItem(ders.get(1).toString(),ders.get(0).toString()));
        }
        jComboBox1.setSelectedIndex(-1);
    }
    
    public void ComboBox2Yenile()
    {
        jComboBox2.removeAllItems();
        bolumler = derslerIslemleri.BolumListele(ID2);
        for(ArrayList bolum:bolumler)
        {
            jComboBox2.addItem(new ComboItem(bolum.get(1).toString(),bolum.get(0).toString()));
        }
        jComboBox2.setSelectedIndex(-1);
    }
    
    public void ComboBox3Yenile()
    {
        jComboBox3.removeAllItems();
        fakulteler = derslerIslemleri.FakulteListele();
        for(ArrayList bolum:fakulteler)
        {
            jComboBox3.addItem(new ComboItem(bolum.get(1).toString(),bolum.get(0).toString()));
        }
        jComboBox3.setSelectedIndex(-1);
    }
    
    public void anamenu(AnaMenu a)
    {
        this.a=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Ekle");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Kaydet");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jTextField1.setToolTipText("Ders ismini giriniz");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2İtemStateChanged(evt);
            }
        });

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3İtemStateChanged(evt);
            }
        });

        jTextField2.setToolTipText("Bu dersi alacak sınıfı giriniz");

        jTextField3.setToolTipText("Vizenin döneme etkisini giriniz");

        jTextField4.setToolTipText("Finalin döneme etkisini giriniz");

        jButton4.setText("AnaMenü");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel1.setText("Ders");

        jLabel2.setText("Sınıf");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Vize");

        jLabel4.setText("Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jTextField2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jTextField1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        if(jComboBox1.getSelectedItem()==null)
        {
            ID=-1;
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }
        else
        {
            Object item = jComboBox1.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID = Integer.parseInt(value);
            
            for(ArrayList ders:dersler)
            {
                if (ders.get(0).toString().equals(value))
                {
                    jTextField1.setText(ders.get(1).toString());

                    ComboItem items;
                    for (int i = 0; i < jComboBox3.getItemCount(); i++)
                    {
                        items = (ComboItem)jComboBox3.getItemAt(i);
                        if (items.getValue().equalsIgnoreCase(ders.get(7).toString()))
                        {
                            jComboBox3.setSelectedIndex(i);
                            break;
                        }
                    }
                    
                    for (int i = 0; i < jComboBox2.getItemCount(); i++)
                    {
                        items = (ComboItem)jComboBox2.getItemAt(i);
                        if (items.getValue().equalsIgnoreCase(ders.get(8).toString()))
                        {
                            jComboBox2.setSelectedIndex(i);
                            break;
                        }
                    }
                    jTextField2.setText(ders.get(4).toString());
                    jTextField3.setText(ders.get(5).toString());
                    jTextField4.setText(ders.get(6).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3İtemStateChanged
        if(jComboBox3.getSelectedItem()==null)
        {
            ID2=-1;
        }
        else
        {
            Object item = jComboBox3.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID2 = Integer.parseInt(value);
        }
        ComboBox2Yenile();
    }//GEN-LAST:event_jComboBox3İtemStateChanged

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        if(jComboBox2.getSelectedItem()==null)
        {
            ID3=-1;
        }
        else
        {
            Object item = jComboBox2.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID3 = Integer.parseInt(value);
        }
    }//GEN-LAST:event_jComboBox2İtemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String dersAdi = jTextField1.getText().toString();
        String deger = jTextField2.getText().toString();
        String deger2 = jTextField3.getText().toString();
        String deger3 = jTextField4.getText().toString();
        if("".equals(dersAdi) || "".equals(deger) || "".equals(deger2) || "".equals(deger3) || ID2==-1 || ID3==-1)
        {
            System.out.println("Boş alanları doldurmadan dersi ekleyemezsiniz");
        }
        else
        {
            int sinif = Integer.parseInt(deger);
            float vizeD= Float.parseFloat(deger2), finalD=Float.parseFloat(deger3);
            boolean tekrar=false;
            for(ArrayList ders:dersler)
            {
                Object item = jComboBox2.getSelectedItem();
                String value = ((ComboItem)item).getValue();
                
                Object item2 = jComboBox2.getSelectedItem();
                String value2 = ((ComboItem)item).getValue();
                
                if(ders.get(1).toString().equals(dersAdi) 
                        && value2.equals(ders.get(7).toString()) 
                        && value.equals(ders.get(8).toString()))
                {
                    tekrar=true;
                }
            }
            if(!tekrar)
            {
                //String dersAdi, int fakulte, int bolum, int sinif, float vizeD, float finalD
                ArrayList veri = new ArrayList();
                veri.add(dersAdi);
                veri.add(ID2);
                veri.add(ID3);
                veri.add(sinif);
                veri.add(vizeD);
                veri.add(finalD);
                derslerIslemleri.Ekle(veri);
                ComboBox1Yenile();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
            }
            else
            {
                System.out.println("Girdiğiniz bilgiler zaten mevcut..");
            }
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(ID==-1)
        {
            System.out.println("İlk önce değiştireceğiniz dersi seçmelisiniz...");
        }
        else
        {
            String dersAdi = jTextField1.getText().toString();
            String deger = jTextField2.getText().toString();
            int sinif = Integer.parseInt(deger);
            float vizeD= Float.parseFloat(jTextField3.getText().toString()), finalD=Float.parseFloat(jTextField4.getText().toString());
            ArrayList veri = new ArrayList();
            veri.add(ID);
            veri.add(dersAdi);
            veri.add(ID2);
            veri.add(ID3);
            veri.add(sinif);
            veri.add(vizeD);
            veri.add(finalD);
            derslerIslemleri.Duzenle(veri);
            ComboBox1Yenile();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jComboBox2.setSelectedIndex(-1);
            jComboBox3.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(ID==-1)
        {
            System.out.println("İlk önce değiştireceğiniz dersi seçmelisiniz...");
        }
        else
        {
            derslerIslemleri.Sil(ID);
            ComboBox1Yenile();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jComboBox2.setSelectedIndex(-1);
            jComboBox3.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<ComboItem> jComboBox1;
    private javax.swing.JComboBox<ComboItem> jComboBox2;
    private javax.swing.JComboBox<ComboItem> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
