
package teslimedilecekproje;

import java.util.ArrayList;

/**
 * @author yusuf
 */
public class DersSecimi extends javax.swing.JFrame {
    /*class ComboItem
    {
        private String key;
        private String value;

        public ComboItem(String key, String value)
        {
            this.key = key;
            this.value = value;
        }

        @Override
        public String toString()
        {
            return key;
        }

        public String getKey()
        {
            return key;
        }

        public String getValue()
        {
            return value;
        }
    }*/
    DersSecimiDB secim = new DersSecimiDB();
    ArrayList <ArrayList> ogrenciler = new ArrayList();
    ArrayList <ArrayList> dersler = new ArrayList();
    ArrayList <ArrayList> alinanDersler = new ArrayList();
    int ID,ID2,ID3;

    /**
     * Creates new form DersSecimi
     */
    public DersSecimi() {
        initComponents();
        setTitle("Öğrenci ile ilgili diğer işlemler");
        setLocation(500, 200);
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
    }

    AnaMenu a;
    
    public void ComboBox1Yenile()
    {
        ogrenciler = secim.Listele();
        jComboBox1.removeAllItems();
        for(ArrayList ders:ogrenciler)
        {
            jComboBox1.addItem(new ComboItem(ders.get(1).toString(), ders.get(0).toString()));
        }
        jComboBox1.setSelectedIndex(-1);
    }
    
    public void ComboBox2Yenile()
    {
        jComboBox2.removeAllItems();
        dersler = secim.Dersler();
        alinanDersler = secim.AlınanDersler();
        if(ID==-1)
        {
            
        }
        else
        {
            boolean tekrar = false;
            for(ArrayList ders:dersler)
            {
                tekrar = false;
                for (ArrayList alinan:alinanDersler)
                {
                    if(ders.get(1).toString().equals(alinan.get(5).toString())
                            && alinan.get(2).toString().equals(String.valueOf(ID)))
                    {
                        tekrar = true;
                    }
                }
                if(!tekrar)
                {
                    for(ArrayList ogrenci:ogrenciler)
                    {
                        if(ogrenci.get(0).toString().equals(String.valueOf(ID))
                                && ogrenci.get(2).toString().equals(ders.get(2).toString())
                                && ogrenci.get(3).toString().equals(ders.get(3).toString()))
                        {
                            jComboBox2.addItem(new ComboItem(ders.get(1).toString(), ders.get(0).toString()));
                        }
                    }
                }

            }
            jComboBox2.setSelectedIndex(-1);
        }
    }
    
    
    public void ComboBox3Yenile()
    {
        jComboBox3.removeAllItems();
        if(ID == -1)
        {
            
        }
        else
        {
            for(ArrayList ders:alinanDersler)
            {
                if(ders.get(2).toString().equals(Integer.toString(ID)))
                    jComboBox3.addItem(new ComboItem(ders.get(5).toString(), ders.get(1).toString()));

            }
            jComboBox3.setSelectedIndex(-1);
        }
    }
    
    public void anamenu(AnaMenu a)
    {
        this.a=a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2İtemStateChanged(evt);
            }
        });

        jButton1.setText("AnaMenü");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Dersi Ekle");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3İtemStateChanged(evt);
            }
        });

        jButton3.setText("Dersi Çıkar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jButton4.setText("Öğrencinin Sınıfını değiştir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox4, 0, 160, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        a.setVisible(true);
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(ID == -1 || ID2==-1)
        {
            System.out.println("Öğrenciyi ve öğrenciye ekleyeceğiniz dersi seçmelisiniz.../n"
                    + "Eğer siltede eleman yoksa bu öğrenciye verilebilecek başka ders yoktur...");
        }
        else
        {
            ArrayList veri = new ArrayList();
            veri.add(ID);
            veri.add(ID2);
            secim.Ekle(veri);
            ComboBox1Yenile();
            ComboBox2Yenile();
            ComboBox3Yenile();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(ID == -1 || ID3==-1)
        {
            System.out.println("Öğrenciyi ve öğrenciden kaldıracağınız dersi seçmelisiniz.../n"
                    + "Eğer siltede eleman yoksa bu öğrenciden silinebilecek başka ders yoktur...");
        }
        else
        {
            for(ArrayList ders:alinanDersler)
            {
                if(ders.get(1).toString().equals(Integer.toString(ID3)) 
                        && ders.get(2).toString().equals(Integer.toString(ID)))
                {
                    System.out.println(Integer.parseInt(ders.get(0).toString()));
                    secim.Sil(Integer.parseInt(ders.get(0).toString()));
                    ComboBox1Yenile();
                    ComboBox2Yenile();
                    ComboBox3Yenile();
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if(ID==-1)
        {
            System.out.println("Öğrenci seçmeden sınıfını değiştiremezsiniz");
        }
        else
        {
            ArrayList veri = new ArrayList();
            veri.add(ID);
            veri.add(Integer.parseInt(jComboBox4.getSelectedItem().toString()));
            secim.Duzenle(veri);
        }
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
        jComboBox4.setSelectedItem("1");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        if(jComboBox1.getSelectedItem() == null)
        {
            ID=-1;
        }
        else
        {
            Object item = jComboBox1.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID = Integer.parseInt(value);
            ComboBox2Yenile();
            ComboBox3Yenile();
            for(ArrayList ogrenci:ogrenciler)
            {
                if(ogrenci.get(0).toString().equals(value))
                {
                    jComboBox4.setSelectedItem(ogrenci.get(4).toString());
                }
            }
        }
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        if(jComboBox2.getSelectedItem() == null)
        {
            ID2=-1;
        }
        else
        {
            Object item = jComboBox2.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID2 = Integer.parseInt(value);
        }
    }//GEN-LAST:event_jComboBox2İtemStateChanged

    private void jComboBox3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3İtemStateChanged
        if(jComboBox3.getSelectedItem() == null)
        {
            ID3=-1;
        }
        else
        {
            Object item = jComboBox3.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID3 = Integer.parseInt(value);
        }
    }//GEN-LAST:event_jComboBox3İtemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    ComboBox1Yenile();
    ComboBox2Yenile();
    ComboBox3Yenile();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DersSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DersSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DersSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DersSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DersSecimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<ComboItem> jComboBox1;
    private javax.swing.JComboBox<ComboItem> jComboBox2;
    private javax.swing.JComboBox<ComboItem> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    // End of variables declaration//GEN-END:variables
}
