
package teslimedilecekproje;

import java.util.ArrayList;

/**
 * @author yusuf
 */
public class Ogrenci extends javax.swing.JFrame {
    ArrayList <ArrayList> bolumler  = new ArrayList<>();
    ArrayList <ArrayList> fakulteler  = new ArrayList<>();
    ArrayList <ArrayList> ogrenciler  = new ArrayList<>();
    int ID,ID2,ID3;
    FakulteBolumDoldur ogrenci = new OgrenciDB();
    AnaMenu a;
    
    /**
     * Creates new form Ogrenci
     */
    public Ogrenci() {
        initComponents();
        setTitle("Öğrenci işlemleri");
        setLocation(500, 200);
        ComboBox1Yenile();
        ComboBox2Yenile();
        ComboBox3Yenile();
    }
    public void ComboBox1Yenile()
    {
        ogrenciler = ogrenci.Listele();
        jComboBox1.removeAllItems();
        for(ArrayList ogrenci:ogrenciler)
        {
            jComboBox1.addItem(new ComboItem(ogrenci.get(1).toString(),ogrenci.get(0).toString()));
        }
        jComboBox1.setSelectedIndex(-1);
    }
    
    public void ComboBox2Yenile()
    {
        jComboBox2.removeAllItems();
        bolumler = ogrenci.BolumListele(ID2);
        for(ArrayList bolum:bolumler)
        {
            jComboBox2.addItem(new ComboItem(bolum.get(1).toString(),bolum.get(0).toString()));
        }
        jComboBox2.setSelectedIndex(-1);
    }
    
    public void ComboBox3Yenile()
    {
        jComboBox3.removeAllItems();
        fakulteler = ogrenci.FakulteListele();
        for(ArrayList bolum:fakulteler)
        {
            jComboBox3.addItem(new ComboItem(bolum.get(1).toString(),bolum.get(0).toString()));
        }
        jComboBox3.setSelectedIndex(-1);
    }
    
    public void anamenu(AnaMenu a)
    {
        this.a=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Ekle");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Düzenle");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.setMaximumSize(new java.awt.Dimension(78, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(78, 30));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("AnaMenü");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTextField1.setToolTipText("Öğrencinin ismini giriniz");

        jTextField2.setToolTipText("Öğrencinin soyadını giriniz");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ön Lisans");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Lisans");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2İtemStateChanged(evt);
            }
        });

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3İtemStateChanged(evt);
            }
        });

        jLabel1.setText("İsim");

        jLabel2.setText("Soyisim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                            .addComponent(jRadioButton2))
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox2, jComboBox3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox2, jComboBox3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jTextField1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        if(jComboBox1.getSelectedItem()==null)
        {
            ID=-1;
            jTextField1.setText("");
            jTextField2.setText("");
        }
        else
        {
            Object item = jComboBox1.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID = Integer.parseInt(value);
            
            for(ArrayList ogrenci:ogrenciler)
            {
                if (ogrenci.get(0).toString().equals(value))
                {
                    jTextField1.setText(ogrenci.get(1).toString());
                    jTextField2.setText(ogrenci.get(2).toString());
                    for(ArrayList fakulte:fakulteler)
                    {
                        if(ogrenci.get(3).toString().equals(fakulte.get(1).toString()))
                        {
                            ComboItem items;
                            for (int i = 0; i < jComboBox3.getItemCount(); i++)
                            {
                                items = (ComboItem)jComboBox3.getItemAt(i);
                                if (items.getValue().equalsIgnoreCase(fakulte.get(0).toString()))
                                {
                                    jComboBox3.setSelectedIndex(i);
                                    break;
                                }
                            }
                            
                            break;
                        }
                    }
                    for(ArrayList bolum:bolumler)
                    {
                        if(ogrenci.get(4).toString().equals(bolum.get(1).toString()))
                        {
                            ComboItem items;
                            for (int i = 0; i < jComboBox2.getItemCount(); i++)
                            {
                                items = (ComboItem)jComboBox2.getItemAt(i);
                                if (items.getValue().equalsIgnoreCase(bolum.get(0).toString()))
                                {
                                    jComboBox2.setSelectedIndex(i);
                                    break;
                                }
                            }
                            break;
                        }
                    }
                    if(ogrenci.get(5).toString().equals("2"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else
                    {
                        jRadioButton2.setSelected(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3İtemStateChanged
        if(jComboBox3.getSelectedItem()==null)
        {
            ID2=-1;
        }
        else
        {
            Object item = jComboBox3.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID2 = Integer.parseInt(value);
        }
        ComboBox2Yenile();
    }//GEN-LAST:event_jComboBox3İtemStateChanged

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        if(jComboBox2.getSelectedItem()==null)
        {
            ID3=-1;
        }
        else
        {
            Object item = jComboBox2.getSelectedItem();
            String value = ((ComboItem)item).getValue();
            ID3 = Integer.parseInt(value);
        }
    }//GEN-LAST:event_jComboBox2İtemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String ad = jTextField1.getText().toString();
        String soyAd = jTextField2.getText().toString();
        if("".equals(ad) || "".equals(soyAd) || ID2 == -1 || ID3 == -1)
        {
            System.out.println("Lütfen bütün alanları doldurunuz...");
        }
        else
        {
            boolean tekrar=false;
            for (ArrayList ogrenci:ogrenciler)
            {
                if(ogrenci.get(1).toString().equals(ad)
                        && ogrenci.get(2).toString().equals(soyAd))
                {
                    tekrar=true;
                }
            }
            if(!tekrar)
            {
                ArrayList veri = new ArrayList();
                veri.add(ad);
                veri.add(soyAd);
                veri.add(ID2);
                veri.add(ID3);
                veri.add(jRadioButton1.isSelected());
                ogrenci.Ekle(veri);
                ComboBox1Yenile();
                jTextField1.setText("");
                jTextField2.setText("");
                ComboBox2Yenile();
                ComboBox3Yenile();
                jRadioButton1.setSelected(true);
            }
            else
            {
                System.out.println("Zaten böyle biri var...");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String ad = jTextField1.getText().toString();
        String soyAd = jTextField2.getText().toString();
        if(ID == -1)
        {
            System.out.println("Değişiklik yapabilmeniz için önce bir öğrenci seçmelisiniz...");
        }
        else if(ad == "" || soyAd == "" || ID2 == -1 || ID3 == -1)
        {
            System.out.println("Bu öğrenciyi silmek için yetersiz bir yöntem.../nDaha kolayı sil e basmak;)");
        }
        else
        {
            ArrayList veri = new ArrayList();
            veri.add(ID);
            veri.add(ad);
            veri.add(soyAd);
            veri.add(ID2);
            veri.add(ID3);
            veri.add(jRadioButton1.isSelected());
            ogrenci.Duzenle(veri);
            ComboBox1Yenile();
            jTextField1.setText("");
            jTextField2.setText("");
            ComboBox2Yenile();
            ComboBox3Yenile();
            jRadioButton1.setSelected(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(ID==-1)
        {
            System.out.println("Birini silebilmek için önce seçmelisiniz...");
        }
        else
        {
            ogrenci.Sil(ID);
            ComboBox1Yenile();
            jTextField1.setText("");
            jTextField2.setText("");
            ComboBox2Yenile();
            ComboBox3Yenile();
            jRadioButton1.setSelected(true);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    ComboBox1Yenile();
    jTextField1.setText("");
    jTextField2.setText("");
    ComboBox2Yenile();
    ComboBox3Yenile();
    jRadioButton1.setSelected(true);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ogrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<ComboItem> jComboBox1;
    private javax.swing.JComboBox<ComboItem> jComboBox2;
    private javax.swing.JComboBox<ComboItem> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
